apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: music-platform-strict-mtls
  namespace: __NAMESPACE__
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: api-allow-trusted-sources
  namespace: __NAMESPACE__
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: api
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces:
              - istio-system
              - __NAMESPACE__
      to:
        - operation:
            ports:
              - "8000"
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: db-allow-api-only
  namespace: __NAMESPACE__
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: db
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - __CLUSTER_DOMAIN__/ns/__NAMESPACE__/sa/__API_SERVICE_ACCOUNT__
      to:
        - operation:
            ports:
              - "5432"
