apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: playcatch-gateway
  namespace: __NAMESPACE__
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - __ISTIO_HOST__
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: playcatch-api-ingress
  namespace: __NAMESPACE__
spec:
  hosts:
    - __ISTIO_HOST__
  gateways:
    - playcatch-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: __API_SERVICE_HOST__
            port:
              number: 8000
