apiVersion: v1
kind: Service
metadata:
  name: {{ include "music-platform.dbServiceName" . }}
  labels:
    {{- include "music-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
spec:
  clusterIP: None
  ports:
    - name: postgres
      port: {{ .Values.db.service.port }}
      targetPort: postgres
      protocol: TCP
  selector:
    {{- include "music-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: db
