{{- if not .Values.db.existingSecret }}
{{- $dbHost := include "music-platform.dbServiceName" . -}}
{{- $secretName := include "music-platform.secretName" . -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- $postgresPassword := "" -}}
{{- if and $existingSecret (hasKey $existingSecret.data "POSTGRES_PASSWORD") -}}
{{- $postgresPassword = (index $existingSecret.data "POSTGRES_PASSWORD" | b64dec) -}}
{{- else if .Values.db.password -}}
{{- $postgresPassword = .Values.db.password -}}
{{- else -}}
{{- $postgresPassword = randAlphaNum 40 -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "music-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ $postgresPassword | quote }}
  DATABASE_URL: {{ printf "postgresql+psycopg://%s:%s@%s:%v/%s" .Values.db.user $postgresPassword $dbHost .Values.db.service.port .Values.db.name | quote }}
{{- end }}
