apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "music-platform.apiServiceAccountName" . }}
  labels:
    {{- include "music-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "music-platform.dbServiceAccountName" . }}
  labels:
    {{- include "music-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
