nameOverride: ""
fullnameOverride: ""

api:
  replicaCount: 1
  image:
    repository: music-platform-api
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
  containerPort: 8000
  resources: {}
  probes:
    liveness:
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 2
      failureThreshold: 3
    readiness:
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 2
      failureThreshold: 3

db:
  image:
    repository: postgres
    tag: "16-alpine"
    pullPolicy: IfNotPresent
  service:
    port: 5432
  name: music_platform
  user: postgres
  password: postgres
  persistence:
    enabled: true
    size: 1Gi
    storageClass: ""
  resources: {}
