nameOverride: ""
fullnameOverride: ""

api:
  replicaCount: 1
  image:
    repository: music-platform-api
    tag: "1.7.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
  containerPort: 8000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  probes:
    startup:
      initialDelaySeconds: 5
      periodSeconds: 2
      timeoutSeconds: 2
      failureThreshold: 30
    liveness:
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 2
      failureThreshold: 3
    readiness:
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 2
      failureThreshold: 3

db:
  image:
    repository: postgres
    tag: "16-alpine@sha256:20edbde7749f822887a1a022ad526fde0a47d6b2be9a8364433605cf65099416"
    pullPolicy: IfNotPresent
  service:
    port: 5432
  probes:
    startup:
      initialDelaySeconds: 0
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 12
    readiness:
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 5
    liveness:
      initialDelaySeconds: 20
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 5
  name: music_platform
  user: postgres
  password: null
  existingSecret: ""
  persistence:
    enabled: true
    size: 1Gi
    storageClass: "standard"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 1Gi
